

# server.yml
server:
  port: 8081


#swagger
  springdoc:
  api-docs:
    enabled: true
    path: /vm-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

#logging
#logging:
#  level:
#    root: INFO
##    root: DEBUG
#    org.springframework.web.client.RestTemplate: DEBUG
#
#  file:
#      path: logs/
#      name: logs/application.log



# application.yml
connect-timeout: 5000
read-timeout: 5000

# config file
item:
  idItem: 1001
  itemCode: B
  itemName: Chocolates
  quantity: 5
  itemCost: 5.0







