

# server.yml
server:
  port: 8081


#swagger
  springdoc:
  api-docs:
    enabled: true
    path: /vm-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

#logging
#logging:
#  level:
#    org.springframework.web.client.RestTemplate: DEBUG
logging:
  level:
    root: INFO
    com.example: DEBUG


# application.yml
connect-timeout: 5000
read-timeout: 5000










